### ISSUE TITLE
xml.etree.ElementTree.ParseError when extracting text from IGC 

### ISSUE THREAD

**Issue by egillanton** [cadia-lvl/ictk#5]
# IssueType Bug report

## Problem

Bug report for `xml.etree.ElementTree.ParseError`

## Steps To Reproduce

```console
(ictk) egillanton@terra:~/ictk$ find /data/risamalheild/2018/rmh1 -type f \( -name "*.xml" -not -name "hdr?.xml" \) |   ./main.py read-igc - rmh.txt --threads 16  --chunksize 400
```
### Output

```console
2020-07-09 11:27:38,983 - Processing IGC. Number of files=2850265
 99%|███████████▌ | 2835200/2850265 [1:06:07<00:21, 714.67it/s]
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/egillanton/.conda/envs/ictk/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/egillanton/.conda/envs/ictk/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/egillanton/.conda/envs/ictk/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/egillanton/ictk/ictk/igc.py", line 55, in get_text_from_file
    root = ET.parse(str(path)).getroot()
  File "/home/egillanton/.conda/envs/ictk/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/home/egillanton/.conda/envs/ictk/lib/python3.8/xml/etree/ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: mismatched tag: line 194, column 846
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./main.py", line 56, in <module>
    cli()
  File "/home/egillanton/.conda/envs/ictk/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/egillanton/.conda/envs/ictk/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/egillanton/.conda/envs/ictk/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/egillanton/.conda/envs/ictk/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/egillanton/.conda/envs/ictk/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./main.py", line 48, in read_igc
    for corpus in igc.get_corpus(files, threads=threads, chunksize=chunksize):
  File "/home/egillanton/ictk/ictk/igc.py", line 40, in get_corpus
    yield from results
  File "/home/egillanton/.conda/envs/ictk/lib/python3.8/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/home/egillanton/.conda/envs/ictk/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/egillanton/.conda/envs/ictk/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/home/egillanton/.conda/envs/ictk/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/egillanton/.conda/envs/ictk/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
xml.etree.ElementTree.ParseError: mismatched tag: line 194, column 846
```

## Fix

Maybe it breaks when there is only one `.xml` file is left to parse and `click` expects a list of strings.

**Comment by egillanton** [comment]
This might help:

```console
(ictk) egillanton@terra:~/ictk$ wc -l rmh.txt 
45236677 rmh.txt
```

**Comment by HaukurPall** [comment]
I will look into this issue. It seems that the file which is being parsed is not correctly formatted. I will try to recreate the issue tomorrow.

**Comment by HaukurPall** [comment]
I found the issue:
The find command is not correctly filtering out the "header" files which are a part of the IGC. The problematic filename is "/data/risamalheild/2018/rmh1/rmh1Hdr.xml", thus the correct find command is:
`find /data/risamalheild/2018/rmh1 -type f \( -name "*.xml" -not -name "*Hdr.xml" \)`
I will update the documentation to update the find command.
